name: Publish Docker image
on:
  release:
    types: [published, released]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    if: ${{ github.event.release.prerelease }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/roger21gm/gos
          tag-sha: true
          tag-semver: |
            {{major}}.{{minor}}s
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          path: ./build
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: ghcr.io/roger21gm/gos
          tag_with_ref: true
